login/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', index, name='index'),
]

mystatus/urls.py
from django.urls import path
from . import views
from .views import index, savestatus

app_name = 'mystatus'
urlpatterns = [
    path('', index),
    path('savestatus/', views.savestatus, name='savestatus'),
]

timeline/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mystatus/', include('mystatus.urls', namespace='mystatus')),
    path('aboutme/', include('aboutme.urls', namespace='aboutme')),
    path('mybooks/', include('mybooks.urls', namespace='mybooks')),
    path('login/', include(('login.urls', 'login'), namespace='login')),
    path('auth/', include('social_django.urls', namespace='social')),
]

mystatus/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
	status_line = models.CharField(max_length=300)
	date = models.DateTimeField(default=timezone.now)

mystatus/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    status_line = forms.CharField(max_length=300, widget=forms.Textarea(attrs={'class' : 'form-status', 'placeholder' : 'Write your status here'}))

    class Meta:
        model = Status
        fields = ('status_line',)
        fields_required = ('status_line',)

mystatus/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import StatusForm
from .models import Status

response = {}

def index(request):
    status = Status.objects.all()
    response['status'] = status
    response['form'] = StatusForm
    html = 'status.html'
    return render(request, html, response)

def savestatus(request):
    form = StatusForm(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['status_line'] = request.POST['status_line']
        status = Status(status_line=response['status_line'])
        status.save()
        return HttpResponseRedirect('/mystatus/')
    return render(request, 'status.html', {'form':form})

mystatus/templates/status.html
{% extends 'base.html' %}

{% block content %}
    <div id="loader"><i class="fa fa-circle-o-notch fa-spin blue-clr"></i></div>
    <div class="container content">
		<div class="page-title font-weight-medium blue-bg white-text" id="hello-title">Hello, apa kabar?</div>
	    <form method="POST" class="form-post" action="{%url 'mystatus:savestatus' %}">
	        {% csrf_token %}
	        {{ form.as_p }}
	        <button type="submit" id="submit" formmethod="POST" formaction="{%url 'mystatus:savestatus' %}" class="addstatus save btn dblue-bg white-text">Add Status
	        </button>
	    </form>
        <div class="page-box white-bg">
       		{% if status %}
       			<div class="table-responsive table-bordered">
                    <table class="table">
                    	<tbody>
                    		{% for data in status %}
                    			<tr>
    		                        <td>{{ data.status_line }}</td>
    		                        <td>{{ data.date }}</td>
    		                    </tr>	
    	                    {% endfor %}
                    	</tbody>
                    </table>
                </div>
            {% else %}
            	<div class="no-status">Post your first status!</div>
            {% endif %}
        </div>
    </div>
{% endblock %}