aboutme/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'aboutme'
urlpatterns = [
    path('', index, name='index'),
    path('subscribe/', subscribePage, name='subscribePage'),
    path('subscribe/check_email', check_email, name='check_email'),
    path('subscribe/submitForm', submitForm, name='submitForm'),
    path('subscribe/getSubscriber', getSubscriber, name='getSubscriber'),
    path('subscribe/getPass', getPass, name='getPass'),
    path('subscribe/checkPass', checkPass, name='checkPass'),
    path('subscribe/deleteSubscriber', deleteSubscriber, name='deleteSubscriber'),
]

login/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', index, name='index'),
]

timeline/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mystatus/', include('mystatus.urls', namespace='mystatus')),
    path('aboutme/', include('aboutme.urls', namespace='aboutme')),
    path('mybooks/', include('mybooks.urls', namespace='mybooks')),
    path('login/', include(('login.urls', 'login'), namespace='login')),
    path('auth/', include('social_django.urls', namespace='social')),
]

aboutme/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Subscribe(models.Model):
	Email = models.EmailField(max_length=100, unique=True)
	Name = models.CharField(max_length=50)
	Password = models.CharField(max_length=30, validators=[MinLengthValidator(8)])

aboutme/forms.py
from django import forms
from .models import Subscribe

class SubscribeForm(forms.ModelForm):
    Email = forms.EmailField(max_length=50, widget=forms.EmailInput(
    	attrs={'class' : 'form-control', 'placeholder' : 'Please fill out your email'}))
    Name = forms.CharField(max_length=20, widget=forms.TextInput(
    	attrs={'class' : 'form-control', 'placeholder' : 'Please fill out your name'}))
    Password = forms.CharField(max_length=30, widget=forms.PasswordInput(
    	attrs={'class' : 'form-control', 'placeholder' : 'Please fill out your password'}))

    class Meta:
        model = Subscribe
        fields = ('Email', 'Name', 'Password')
        fields_required = ('Email', 'Name', 'Password')

aboutme/views.py
from django.shortcuts import render
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from .forms import SubscribeForm
from .models import Subscribe
from django.core import serializers
import json


def index(request):
    html = 'aboutme.html'
    return render(request, html)

def subscribePage(request):
    response = {}
    response['form'] = SubscribeForm
    html = 'subscribe.html'
    return render(request, html, response)

def check_email(request):
    email = request.GET.get('q', '')
    response = {'valid' : None, 'exist' : None, 'messages' : []}
    try:
        validate_email(email)
    except ValidationError as error:
        response['valid'] = False
        response['messages'] = error.messages
    else:
        response['valid'] = True
        if (Subscribe.objects.filter(Email=email)):
            response['exist'] = True
            response['messages'] = ['This email has been used before, please use another email']
        else:
            response['exist'] = False
    return JsonResponse(response)

def submitForm(request):
    form = SubscribeForm(request.POST or None)
    response = {'success' : None}
    if form.is_valid():
        form.save()
        response['success'] = True
        return JsonResponse(response)
    else:
        response = JsonResponse({'success': False})
        response.status_code = 403
        return response

def getSubscriber(request):
    subscriber = list(Subscribe.objects.values('Name', 'Email').order_by('Name'))
    return JsonResponse({'subscribers': subscriber})

def getPass(request):
    subscriber = list(Subscribe.objects.values('Name', 'Email', 'Password').order_by('Name'))
    return JsonResponse({'subscribers': subscriber})

def checkPass(request):
    email = request.GET.get('email', '')
    response = {'match' : None}
    password = request.GET.get('pass', '')
    userPass = Subscribe.objects.filter(Email=email).values_list('Password', flat=True)
    if (password == list(userPass)[0]):
        response['match'] = True
    else:
        response['match'] = False
    return JsonResponse(response)

def deleteSubscriber(request):
    user = request.GET.get('email', '')
    response = {}
    Subscribe.objects.filter(Email=user).delete()
    response['deleted'] = True
    return JsonResponse(response)

aboutme/templates/aboutme.html
{% extends 'base.html' %}

{% block content %}
	<div id="loader"><i class="fa fa-circle-o-notch fa-spin blue-clr"></i></div>
    <div class="container content">
    	<div class="row">
		  	<div class="prof col blue-bg d-flex align-items-center" id="prof">
		  		<div class="profile">
				  	<div class="my-photo">
				  		{% load static %}
		                <img src="{% static "img/me.jpg" %}" class="img-fluid img-thumbnail mx-auto d-block rounded-circle" id="profpic">
		            </div>
		            <div class="t info white-text font-weight-bold text-center">
		            	<div>ALYA ZAHRA</div>
		            </div>
		        </div>
		  	</div>
		  	<div class="col white-bg d-flex align-items-center">
		  		<div class="t contacts font-weight-normals text-center mx-auto">
		  			<p class="font-weight-bold">CONTACTS</p>
	                <p><i class="fa fa-whatsapp"></i> 087863224506</p>
	                <p><i class="fa fa-envelope"></i> alya.zahra71@ui.ac.id</p>
	                <p><i class="fa fa-gitlab"></i> alzahra</p>
	                <p><i class="fa fa-instagram"></i> alyazahra22</p>
	                <p><u class="subscribe"><a href="{% url 'aboutme:subscribePage' %}">Subscribe now!</a></u></p>
	            </div>
		  	</div>
		  	<div class="row mypanel dblue-bg white-text" id="activity" name="panel">
		  		<div class="col-10"><div class="t text-center">Activities</div></div>
		  		<div class="col-2"><div class="fa fa-toggle-down"></div></div>
			</div>
			<div class="row t answer white-bg" id="act-ans">
				<p><i class="fa fa-circle blue-clr"></i> Student of Faculty of Computer Science UI (2017)</p>
				<p><i class="fa fa-circle blue-clr"></i> Member of Academic Division of PMB Fasilkom UI 2018</p>
			</div>
			<div class="row mypanel dblue-bg white-text" id="skill" name="panel">
		  		<div class="col-10"><div class="t text-center">Skills</div></div>
		  		<div class="col-2"><div class="fa fa-toggle-down"></div></div>
			</div>
			<div class="row answer white-bg" id="skill-ans">
				<div class="progress">
    				<div class="progress-bar white-text t blue-bg" style="width:80%;">Adobe Illustrator</div>
  				</div>
  				<div class="progress">
    				<div class="progress-bar white-text t blue-bg" style="width:95%;">Paint Tool SAI</div>
  				</div>
  				<div class="progress">
    				<div class="progress-bar white-text t blue-bg" style="width:70%;">Java</div>
  				</div>
  				<div class="progress">
    				<div class="progress-bar white-text t blue-bg" style="width:70%;">Python</div>
  				</div>
			</div>
			<div class="row mypanel dblue-bg white-text" id="experience" name="panel">
		  		<div class="col-10"><div class="t text-center">Experiences</div></div>
		  		<div class="col-2"><div class="fa fa-toggle-down"></div></div>
			</div>
			<div class="row t answer white-bg" id="exp-ans">
				<p><i class="fa fa-circle blue-clr"></i> Design & Creative in SIWAK-NG 2018</p>
				<p><i class="fa fa-circle blue-clr"></i> Design & Creative in BETIS 2017</p>
			</div>
			<div class="row mypanel dblue-bg white-text" id="achieve" name="panel">
		  		<div class="col-10"><div class="t text-center">Achievements</div></div>
		  		<div class="col-2"><div class="fa fa-toggle-down"></div></div>
			</div>
			<div class="row t answer white-bg" id="ach-ans">
				<p><i class="fa fa-circle blue-clr"></i> Ranked 10th in Province Tryout of National Exam (2014)</p>
			</div>
		</div>
    </div>
{% endblock %}

aboutme/templates/subscribe.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}<script type="text/javascript" src="{% static "js/subscribe.js" %}"></script>{% endblock %}

{% block content %}
	<div id="loader"><i class="fa fa-circle-o-notch fa-spin blue-clr"></i></div>
    <div class="container content">
    	<div class="page-title font-weight-medium blue-bg white-text">Subscribe to this site now!</div>
    	<form class="subform text-center mx-auto" method="POST" class="form-post" id="subscribeForm">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            	<div class="row" id="rowform">
            		<div class="col-2 t">
            			{{ field.label_tag }}
            		</div>
            		<div class="col-10">
				 		{{ field }}
				 	</div>
				 	{% for error in field.errors %}
				 	<div id="{{ field.name }}_error">
				 		<p>{{ error|escape }}</p>
				 	</div>
				 	{% endfor %}
				</div>
			{% endfor %}
            <button class="t save btn dblue-bg white-text" id="subbutton" disabled="true">Subscribe</button>
        </form>
        <h2 id="success" class="t font-weight-medium text-success text-center" style="display: none;">Your data has been saved.</h3>
  		<h2 id="fail" class="t font-weight-medium text-danger text-center" style="display: none;">Your data is invalid.</h3>
        <div id="subtable">
            <div class="table-responsive table-bordered">
                <table class="table" id="subtab">
                    <thead class="thead-dark text-center">
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Unsubscribe</th>
                        </tr>
                    </thead>
                    <tbody class="text-center" id="sublist">
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal fade" id="unsubmodal" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="ModalLongTitle">Are You Sure You Want to Unsubscribe?</h5>
                    </div>
                    <div class="x modal-body">
                        Confirm your password below:
                        <input class="form-control" placeholder="Your password here" type="password" id="id_confirmpass" value="">
                        <div id="confirmpass_error"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="x btn dblue-bg white-text" id='confirmunsub' value=''>Confirm</button>
                        <button type="button" class="x btn btn-danger white-text" data-dismiss="modal" id="cancelunsub">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="afterUnsub" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="x modal-body">
                        You have been unsubscribed from this site.
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}