login/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', index, name='index'),
]

mybooks/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'mybooks'
urlpatterns = [
    path('', index),
    path('logout/', logout, name='logout'),
    path('saveBook/', saveBook, name='saveBook'),
    path('deleteBook/', deleteBook, name='deleteBook'),
    path('checkBook/', checkBook, name='checkBook'),
    path('checkLogin/', checkLogin, name='checkLogin'),
    path('<str:category>/', getJson, name='getJson'),
]

timeline/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mystatus/', include('mystatus.urls', namespace='mystatus')),
    path('aboutme/', include('aboutme.urls', namespace='aboutme')),
    path('mybooks/', include('mybooks.urls', namespace='mybooks')),
    path('login/', include(('login.urls', 'login'), namespace='login')),
    path('auth/', include('social_django.urls', namespace='social')),
]

mybooks/models.py
from django.db import models

# Create your models here.

mybooks/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse	
import json
import requests

# Create your views here.
def index(request):
	response = {}
	if 'myStars' in request.session.keys():
		response['stars'] = request.session['myStars']
	else:
		request.session['myStars'] = 0
		response['stars'] = request.session['myStars']
	html = 'mybooks.html'
	return render(request, html, response)

def saveBook(request):
	response = {}
	response['saved'] = None
	bookValue = request.GET.get('value', '')
	if 'favorited' in request.session.keys() and 'myStars' in request.session.keys():
		favList = request.session['favorited']
		if bookValue not in favList:
			favList.append(bookValue)
			request.session['favorited'] = favList
			request.session['myStars'] += 1
	else:
		request.session['favorited'] = []
		request.session['favorited'].append(bookValue)
		request.session['myStars'] = 1
	response['saved'] = True
	return JsonResponse(response)

def deleteBook(request):
	response = {}
	response['deleted'] = None
	bookValue = request.GET.get('value', '')
	favList = request.session['favorited']
	favList.remove(bookValue)
	request.session['favorited'] = favList
	request.session['myStars'] -= 1
	response['deleted'] = True
	return JsonResponse(response)

def checkBook(request):
	response = {}
	response['exist'] = None
	bookValue = request.GET.get('value', '')
	if 'favorited' in request.session.keys():
		favList = request.session['favorited']
		if bookValue in favList:
			response['exist'] = True
		else:
			response['exist'] = False
	else:
		response['exist'] = False
	return JsonResponse(response)

def checkLogin(request):
	response = {}
	response['loggedIn'] = None
	if request.user.is_authenticated:
		response['loggedIn'] = True
	else:
		response['loggedIn'] = False
	return JsonResponse(response)

def logout(request):
	request.session.flush()
	return HttpResponseRedirect('/../mybooks')

def getJson(request, category):
	url = "https://www.googleapis.com/books/v1/volumes?q=" + category
	json_data = json.loads(requests.get(url).text)
	return JsonResponse(json_data)

mybooks/templates/mybooks.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}<script type="text/javascript" src="{% static "js/mybooks.js" %}"></script>{% endblock %}

{% block content %}
	<div id="loader"><i class="fa fa-circle-o-notch fa-spin blue-clr"></i></div>
    <div class="container content">
    	<div class="top-box blue-bg d-block mx-auto" id="books-box">
			<div class="t white-text text-center">
				My Favorited Books
			</div>
		</div>
		<div class="star text-center">
			<div class="fa fa-star yellow-clr" id="star-counter"></div>
            {% if user.is_authenticated %}
			    <a class="t" id="number"> {{ stars }} </a>
            {% else %}
                <a class="t" id="number"> 0 </a>
            {% endif %}
		</div>
        {% if user.is_authenticated %}
            <p class="t text-center">Hello, {{ user.username }}</p>
            <div class="x align-items-center text-center">
                <button class="btn btn-danger mx-auto sessionbtn"><a id="google-button" href="{% url 'mybooks:logout' %}">Log Out</a></button>
            </div>
        {% else %}
            <div class="x align-items-center text-center">
                <button class="save btn mx-auto sessionbtn"><a id="google-button" href="{% url 'login:index' %}">Log In</a></button>
            </div>
        {% endif %}
        <div class="input-group add-on">
            <input class="form-control" placeholder="Search book category" type="text" id="search-bar" value="">
            <div>
            <button class="btn btn-default searchbtn" type="submit" id="search-btn"><i class="fa fa-search blue-clr"></i></button></div>
        </div>
        <div id="mytable">
    		<div class="table-responsive table-bordered">
                <table class="table" id="tab">
                    <thead class="thead-dark text-center">
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Image</th>
                            <th scope="col">Title</th>
                            <th scope="col">Authors</th>
                            <th scope="col">Publishers</th>
                            <th scope="col">Published Date</th>
                            <th scope="col">Add to Favorites</th>
                        </tr>
                    </thead>
                	<tbody class="text-center" id="booklist">
                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal fade" id="beforeLogin" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="x modal-body">
                        You need to log-in first.
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}